config/urls.py
from allauth.account.views import password_change
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns
from rest_framework_swagger.views import get_swagger_view

# from company.views import company_update_view
from products.views import product_create_view
from project.views import home_view, oops_view
from lawyerd.users.views import company_update_view

schema_view = get_swagger_view(title='Lawyerd API')

urlpatterns = [
        # path('capture/',  include('screamshot.urls', namespace='screamshot'), name='screamshot'),
        path('api/', schema_view, name='swagger'),
        path('api/v1/', include('api.v1.urls')),
        # path('feedback/', view=company_update_view),
        path("oops/", view=oops_view, name="oops"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
        path('rosetta/', include('rosetta.urls')),
        # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
        path("", view=home_view, name="home"),
        path("faq/", TemplateView.as_view(template_name="pages/faq.html"), name="faq"),
        path("about_us/", TemplateView.as_view(template_name="pages/about_us.html"), name="about_us"),
        path("contact_us/", TemplateView.as_view(template_name="pages/contact_us.html"), name="contact_us"),


        path("terms/", TemplateView.as_view(template_name="pages/terms.html"), name="terms"),
        path("policy/", TemplateView.as_view(template_name="pages/policy.html"), name="policy"),

        # path("profile/", TemplateView.as_view(template_name="account/password_change.html"), name="profile"),
        path("profile/", password_change, {'template_name': 'account/password_change.html', }, name="profile"),

        path("company/", view=company_update_view, name="company"),
        path("products/", view=product_create_view, name="products"),
        # path("pricing_old/", TemplateView.as_view(template_name="pages/pricing.html"), name="pricing_old"),

        # Django Admin, use {% url 'admin:index' %}
        path(settings.ADMIN_URL, admin.site.urls),

        # User management
        path("users/", include("users.urls", namespace="users")),
        path("accounts/", include("allauth.urls")),

        # Your stuff: custom urls includes go here
        path('explorer/', include('explorer.urls')),

        path('products/', include('products.urls')),
        path('orders/', include('complaint.urls')),

        path('plans-payments/', include('plans_payments.urls')),
        path('plan/', include('plans.urls')),

        path('feedback/', include('feedback.urls')),

    )

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

lawyerd/api/v1/urls.py
from django.urls import path

from api.v1.views import ComplaintList, ComplaintAdd, ComplaintSetStatus, ComplaintDetailList, \
    ProductView, ProductDelete, AnonymousSearch

# GetSiteScreenshot, GetSitesList, GetSiteHosting, GetSiteHostingAbuseEmail

app_name = "api"
urlpatterns = [
    path('anonymous_search_view/', AnonymousSearch.as_view(), name='anonymous_sarch'),

    path('complaint_list/', ComplaintList.as_view({'get': 'list'}), name='complaint_list'),
    path('complaint_add/', ComplaintAdd.as_view(), name='complaint_add'),
    path('complaint_setstatus/', ComplaintSetStatus.as_view(), name='complaint_cancel'),

    path('complaint_details_list/', ComplaintDetailList.as_view({'get': 'list'}), name='complaint_details_list'),

    path('product_view/', ProductView.as_view({'get': 'list'}), name='product_list'),
    path('product_delete/', ProductDelete.as_view(), name='product_delete'),

    # internal
    # path('get_sites_list/', GetSitesList.as_view(), name='get_sites_list'),
    # path('get_site_screenshot/', GetSiteScreenshot.as_view(), name='get_site_screenshot'),
    # path('get_site_hosting/', GetSiteHosting.as_view(), name='get_site_hosting'),
    # path('get_site_hosting_abuse_email/', GetSiteHostingAbuseEmail.as_view(), name='get_site_hosting_abuse_email'),
]

lawyerd/feedback/urls.py
from django.urls import path
from .views import feedback_view

app_name = "feedbacks"
urlpatterns = [
    path("feedback", view=feedback_view, name="feedback"),
]

lawyerd/products/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

# from lawyerd.users.views import (
#     user_redirect_view,
#     user_update_view,
#     user_detail_view,
# )

app_name = "products"
urlpatterns = [

]

lawyerd/users/urls.py
from django.urls import path

from lawyerd.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lawyerd/products/models.py
import os
import uuid

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models  # , connection
# from django.db.models import Q, Index
from django_extensions.db.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _
from model_utils import Choices

PRODUCT_STATUS = Choices(
    (0, 'waiting', _('waiting')),
    (1, 'accepted', _('accepted')),
    # (2, 'complete', _('complete')),
    (3, 'cancelled', _('cancelled')),
    # (4, 'stopped', _('stopped')),
)

PRODUCT_TYPE = Choices(
    (0, 'game', _('Game')),
    (1, 'software', _('Software')),
    (2, 'photo', _('Photo')),
    (3, 'picture', _('Picture')),
    (4, 'course', _('Course')),
    (5, 'brand', _('Brand')),
)


def validate_product_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.pdf', ]
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension.')


def product_get_file_path(instance, filename):
    ext = filename.split('.')[-1].lower()
    filename = "%s.%s" % (uuid.uuid4(), ext)
    res = os.path.join(f'user_product_{instance.user_id}', filename)
    return res


class Product(TimeStampedModel, models.Model):
    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=False, verbose_name=_('The name of the product'))
    document = models.FileField(upload_to=product_get_file_path, null=True, blank=False,
                                validators=[validate_product_file_extension],
                                verbose_name=_(
                                    'Proof of product rights (Trademark from Global Brand Database or national registers)'))  # noqa
    document_file_name = models.CharField(max_length=200, blank=False, verbose_name=_('Document file name'))
    status = models.IntegerField(choices=PRODUCT_STATUS, blank=False, default=PRODUCT_STATUS.waiting, db_index=True,
                                 help_text=_('status'))
    itype = models.IntegerField(choices=PRODUCT_TYPE, blank=False, default=PRODUCT_TYPE.game, db_index=True,
                                verbose_name=_('Type of product'))

    def __str__(self):
        return f'{self.id}-{self.user}-{self.document}'

lawyerd/api/v1/views.py
# api/views.py
import hashlib
from random import randrange

from django.db.models import Value, Sum, IntegerField, Window, Count
from django.http import HttpResponse
from django.db.models import CharField, Value

from rest_framework import generics, status
from rest_framework.authentication import TokenAuthentication
from rest_framework.generics import get_object_or_404
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework import exceptions

from rest_framework.views import APIView
from rest_framework.response import Response

from api.v1.serializers import ComplaintSerializer, ComplaintSetStatusSerializer, ProductSerializer, \
    ComplaintDetailsSerializer, \
    SiteScreenshotSerializer, GetSitesListSerializer, SiteHostingAbuseEmailSerializer, SiteHostingSerializer

from complaint.models import Complaint, ComplaintDetail, STATUS
# get_sites_list, \
# get_site_hosting, \
# get_site_hosting_abuse_email, get_site_screenshot
from products.models import Product, PRODUCT_STATUS
from project.views import validate_oops_page
from config.settings.base import API_KEY_INTERNAL
from config.celery_app import app


@permission_classes([IsAuthenticated])
class ComplaintList(ModelViewSet):
    """
    Get site Orders
    """

    serializer_class = ComplaintSerializer

    def get_queryset(self, ):
        qs = Complaint.objects.filter(user=self.request.user) \
            .annotate(status_value=Value(STATUS.waiting, output_field=IntegerField())) \
            .values('id',
                    'created',
                    'modified',
                    'product__name',
                    'search_text',
                    # 'email',
                    # 'site_count',
                    'status',
                    'status_value',
                    )
        return qs


# from celery.task import Task
#
#
# class MyTask(Task):
#     name = "myapp.mytask"
#
#     def run(self, x, y):
#         return x * y


@permission_classes([IsAuthenticated])
class ComplaintAdd(generics.GenericAPIView):
    """
    Add Order
    """

    serializer_class = ComplaintSerializer

    # serializer_class = ComplaintAddSerializer

    def post(self, request, *args, **kwargs):
        # add2().delay()
        # MyTask.delay(2, 2)
        # return Response('{}')
        ##########################

        # check if need oops page
        res = validate_oops_page(request)

        # nned show oopspage
        if res['show_oops_page']:
            return Response(res)

        # send_to_email = self.request.data['email'] if self.request.user.is_superuser else ''
        # oops_page = False
        site_count = 20
        search_text = self.request.data['search_text'].strip()

        product_id = int(self.request.data['product_id'])
        product = Product.objects.filter(user=self.request.user, status__in=[PRODUCT_STATUS.accepted],
                                         id=product_id).first()

        # not enter search text or selected product
        if not (search_text or product):
            return Response()

        # error_handler('dffghfgh')

        # all fine, WORK !
        complaint_object = Complaint.objects.create(
            user=self.request.user,
            search_text=search_text,
            product=product,
            site_count=site_count,
        )

        res = {
            'oops_page': False,
            'search_results': 1,
        }

        return Response(res)


@app.task(bind=True)
def add2(self):
    print('fghfghfgh')
    return 77


# @app.task()
# def error_handler(uuid):
#     result = uuid
#
#     print('Task {0} raised exception: {1!r}\n{2!r}'.format(
#           uuid, 'exc', result.traceback))


@permission_classes([IsAuthenticated])
class ComplaintDetailList(ModelViewSet):
    """
    Get order details
    """

    serializer_class = ComplaintDetailsSerializer

    def get_queryset(self, ):
        qs = ComplaintDetail.objects.filter(complaint__user=self.request.user)
        if self.request.query_params["complaint_id"]:
            qs = qs.filter(complaint=self.request.query_params["complaint_id"])
        # .values('id', 'created', 'email', 'email_count', 'status', 'status_value')

        # print(f'qs = {qs}')

        return qs


@permission_classes([IsAuthenticated])
class ComplaintSetStatus(generics.GenericAPIView):
    """
    Set Order Status
    """
    # parser_classes = (MultiPartParser, FormParser)
    # queryset = models.Uplist.objects.all()
    # serializer_class = serializers.UplistSerializer
    serializer_class = ComplaintSetStatusSerializer

    # serializers = OrderSetStatusSerializer

    def post(self, request, *args, **kwargs):
        order = get_object_or_404(Complaint, id=request.data['id'],
                                  status__in=[STATUS.waiting, STATUS.processing])
        # order = Order.get_ob objects.filter(id=request.data['id'], status__in=[0, 1]).update(status=3)
        order.status = STATUS.cancelled
        order.save()

        # added function here
        return Response()


@permission_classes([IsAuthenticated])
class ProductView(ModelViewSet):
    """
    Get user product
    """

    serializer_class = ProductSerializer

    def get_queryset(self, ):
        qs = Product.objects.filter(user=self.request.user)
        # .values('id', 'created', 'email', 'email_count', 'status', 'status_value')

        return qs


@permission_classes([IsAuthenticated])
class ProductDelete(generics.GenericAPIView):
    """
    Delete Product (not yet accepted)
    """

    # parser_classes = (MultiPartParser, FormParser)
    # queryset = models.Uplist.objects.all()
    # serializer_class = serializers.UplistSerializer
    serializer_class = ComplaintSetStatusSerializer

    # serializers = OrderSetStatusSerializer

    def post(self, request, *args, **kwargs):
        qs = Product.objects.filter(id=int(self.request.data['id']), user=self.request.user,
                                    status__in=[PRODUCT_STATUS.waiting])
        qs.delete()

        return Response()


# region 'internal services'
class APIKeyAuthentication(TokenAuthentication):
    """
    API Key token based authentication
    """

    def authenticate(self, request):
        user = None
        token = request.data.get('api_key', None)

        if API_KEY_INTERNAL != token:
            raise exceptions.AuthenticationFailed('Invalid API Key.')

        return user, token


# class GetSitesList(generics.ListAPIView):
#     """
#     Get sites list from url/search text
#     """
#     serializer_class = GetSitesListSerializer
#     authentication_classes = (APIKeyAuthentication,)
#
#     # def get_serializer(self, *args, **kwargs):
#     #     serializer_class = self.get_serializer_class()
#     #     kwargs['context'] = self.get_serializer_context()
#     #     # if self.action == 'create':
#     #     #     kwargs['many'] = True
#     #     return serializer_class(*args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         search_text = self.request.data['search_text']
#         product_name = self.request.data['product_name']
#         results_count = int(self.request.data['results_count'])
#
#         res = get_sites_list(search_text, product_name, results_count)
#         return Response(res)
#
#
# class GetSiteHosting(generics.GenericAPIView):
#     """
#     Get site hosting (for internal use only)
#     """
#     serializer_class = SiteHostingSerializer
#     authentication_classes = (APIKeyAuthentication,)
#
#     def post(self, request, *args, **kwargs):
#         url = self.request.data['url']
#
#         res = get_site_hosting(url)
#         return HttpResponse(res)
#
#
# class GetSiteHostingAbuseEmail(generics.GenericAPIView):
#     """
#     Get site hosting abuse email (for internal use only)
#     """
#     serializer_class = SiteHostingAbuseEmailSerializer
#     authentication_classes = (APIKeyAuthentication,)
#
#     def post(self, request, *args, **kwargs):
#         res = None
#         url = self.request.data['url']
#
#         res = get_site_hosting_abuse_email(url)
#         return HttpResponse(res)
#
#
# class GetSiteScreenshot(generics.GenericAPIView):
#     """
#     Get site screenshot (for internal use only)
#     """
#     serializer_class = SiteScreenshotSerializer
#     authentication_classes = (APIKeyAuthentication,)
#
#     def post(self, request, *args, **kwargs):
#         url = self.request.data['url']
#
#         res = get_site_screenshot(url)
#         return HttpResponse(res, content_type="image/png")
#

class AnonymousSearch(APIView):
    """
    Simple mathematical convert function for anonymous search
    """

    def post(self, request, *args, **kwargs):
        s = request.data['search_text']
        # i = int(hashlib.sha256(s.encode('utf-8')).hexdigest(), 16) % 10 ** 8

        i = randrange(99, 500)
        return Response({
            'search_results': i
        })

# endregion

lawyerd/complaint/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render

lawyerd/templates/pages/_______home_unauthorized_search_form_inline.html
{% load i18n static %}

<form action="{% url 'account_signup' %}" id="anonymous_search_form_after_show" class="form-inline ">
    {% csrf_token %}
  <input id="anonymous_search_input" class="form-control" type="search" name="search_text"
         disabled
         placeholder="{% trans 'Enter keywords for start' %}"
         aria-label="{% trans 'Search' %}">
  <button id="account_register" class="btn btn-primary" type="submit">{% trans "To try one more times" %}</button>
</form>

lawyerd/templates/pages/_home_authorized_js.html
{% load i18n static %}

<script>
    $(document).ready(function () {
        let ButtonCancel = `
          <button class="flex btn btn-danger" data-action="0" data-toggle="tooltip" data-placement="top" data-status="1"
            title="{% trans "Cancel" %}">
              {% trans "Cancel" %}
          </button>`;

        let ButtonDetail = `
          <button class="flex btn btn-primary" data-action="1" data-toggle="tooltip" data-placement="top"
            title="{% trans "Detail" %}">
              {% trans "Detail" %}
          </button>`;

        {#data-toggle="lightbox" data-title="Screenshot" data-footer=""#}

        let ButtonScreenshot = `
          <button class="flex btn btn-info" data-action="2" data-toggle="tooltip" data-placement="top"    data-toggle="lightbox" data-title="Screenshot" data-footer=""
            title="{% trans "Screenshot" %}">
            <i class="fa fa-eye" aria-hidden="true"></i>
            {# {% trans "Screenshot" %}#}
          </button>`;


        {#Orders#}
        let table_complaints = $('#complaints').DataTable({
            "serverSide": true,
            "ajax": "{% url 'api:complaint_list' %}?format=datatables",
            "columns": [
                {
                    title: "ID",
                    data: "id",
                    className: 'td__id',
                },

                {
                    title: "Date",
                    data: "created",
                    className: 'td__created',
                    render: function (data, type, row) {
                        return moment(data).format("DD.MM.YYYY HH:mm:ss");
                    }

                },

                {
                    title: "Product",
                    data: "product",
                    className: 'td__product',
                },

                {
                    title: "Search keywords/Link",
                    data: "query",
                    {#className: 'td__query',#}
                    render: function (data, type, row) {
                        return isUrlValid(data) ? `<a href="${data}">${data}</a>` : data
                    }
                },

                /*
                {
                    title: "email",
                    data: "email",
                    className: 'td__email'
                },


                {
                    title: "site_count",
                    data: "site_count",
                    className: 'td__site_count',
                },
                */

                {
                    title: "status_value",
                    data: "status_value",
                    visible: false,
                },

                {
                    title: "Status",
                    data: "status",
                    className: 'td__status',
                    render: function (data, type, row) {
                        let res = data;

                        switch (data) {
                            case 0:
                                res = `Queue position: ${row['status_value']} ${ButtonCancel}`;
                                break;
                            case 1:
                                res = `
                                        <ul class="">
                                          <li>
                                            <p><span>in progress: ${row['status_value']}%</span></p>
                                            <div class="bar-wrap">
                                              <span class="bar-fill" style="width: ${row['status_value']}%;"></span>
                                            </div>

                                            ${ButtonCancel}
                                            ${ButtonDetail}
                                          </li>
                                        </ul>
                                        `;

                                break;
                            case 2:
                                res = `<span> Completed ${ButtonDetail}</span>`;
                                break;
                            case 3:
                                res = `<span> Canceled ${ButtonDetail}</span>`;
                                break;
                        }

                        return res;
                    }
                },
            ]
        });

        let current_complaint_id = 0;

        {#Order Details#}
        let table_complaints_details = $('#complaint_details').DataTable({
            "serverSide": true,
            "paging": false,
            "searching": false,
            "info": false,
            "ajax":
                {
                    "url": "{% url 'api:complaint_details_list' %}",
                    "data": function (d) {
                        d.format = "datatables";
                        d.complaint_id = current_complaint_id;
                    }
                },

            {#"data": {"id": 335},#}
            {#"ajax": "{% url 'api:order_details_list' %}?format=datatables&id="+current_order_id,#}
            "columns": [
                {
                    title: "ID",
                    data: "id",
                    className: 'td__id'
                },

                /*
                                {
                                    title: "order_id",
                                    data: "order_id",
                                },

                 */


                {
                    title: "Date",
                    data: "created",
                    className: 'td__created',
                    render: function (data, type, row) {
                        return moment(data).format("DD.MM.YYYY HH:mm:ss");
                    }
                },

                {
                    title: "Infringing site",
                    data: "site",
                    className: 'td__site',
                    {#width: "600px",#}
                    render: function (data, type, row) {
                        return `
                              <span class="href_dots_ended">
                                <a href="${data}">${data}</a>
                              {#  <a href="${data}">${data}</a>#}
                              </span>`
                        // return isUrlValid(data) ? `<a href="${data}">${data}</a>` : data
                    }
                },

                /*
                {
                    title: "hosting",
                    data: "hosting",
                    className: 'td__hosting'
                },

                {
                    title: "abuse email",
                    data: "email",
                    className: 'td__email'
                },
                */


                {
                    title: "Screenshot",
                    data: "screenshot",
                    className: 'td__screenshot',
                    render: function (data, type, row) {
                        return ButtonScreenshot;

                    },
                    render2: function (data, type, row) {
                        let res = data;

                        if (data) {
                            res = `
                              <a href="${data}" data-toggle="lightbox" data-title="Screenshot" data-footer="">
                                <img src="${data}" class="img-fluid">
                              </a>
                              `;
                        }
                        return res
                    }


                },

                {
                    title: "Status",
                    data: "status",
                    className: 'td__status',
                    render: function (data, type, row) {
                        let res = data;

                        switch (data) {
                            case 0:
                                res = `in process`;
                                break;
                            case 1:
                                res = `completed`;

                                break;
                            case 2:
                                res = `Error!`;
                                break;
                            {#case 3:#}
                            {#    res = 'Canceled' + `${ButtonDetail}`;#}
                            {#    break;#}
                        }

                        return res;
                    }
                },
            ]
        });
        {#Order Details#}

        {#var jTarget = $('body');#}

        {#$('#order_details').wrap('<div id="hide" style="display:none"/>');#}

        $("#authorised_search_form").on("submit", function (event) {
            event.preventDefault();

            const form_data = $(this).serialize();
            console.log(form_data);
            {#jTarget.ajaxloader(); // start/resume the loader#}
            {#console.log($(this).serializeArray());#}

            $.ajax({
                type: "POST",
                url: "{% url 'api:complaint_add' %}",

                data: form_data,
                beforeSend: function (xhr) {
                    SpinnerShow();
                },
                success: function (msg) {
                    if (msg['oops_page'] === true) {
                        window.location.href = {% url "oops" %};
                    }

                    table_complaints.ajax.reload();
                    //$('#search_results')[0].innerText = numberWithCommas(msg['search_results']);

                },

                error: function () {
                    alert("failure");
                    {#window.location.reload(false);#}
                },
            }).done(function (html) {
                SpinnerHide();

                table_complaints.ajax.reload();
                table_complaints.draw();
                table_complaints_details.ajax.reload();
                table_complaints_details.draw();

            });

        });


        // Sort by column 1 and then re-draw
        table_complaints
            .order([1, 'desc'])
            .draw();

        table_complaints_details
            .order([1, 'desc'])
            .draw();

        $('#complaints tbody').on('click', 'button', function () {
            let data = table_complaints.row($(this).parents('tr')).data();
            let id = data['id'];

            // кнопки действий
            let action = parseInt(this.getAttribute('data-action'));
            let status = parseInt(this.getAttribute('data-status'));

            switch (action) {
                case 0:
                    SetNumberStatus(this, id, status);
                    break;

                case 1:
                {#ShowOrderDetails(id);#}
                    console.log(`open complaint details: ${id}`);
                    current_complaint_id = id;
                    $('#current_complaint_id')[0].innerText = `# ${id}`;

                    $('#complaints_details_div').show();
                    table_complaints_details.draw();
                {#table_order_details.columns(1).search(`^${id}$` , true).draw();#}
                {#table_order_details.columns(1).search(`^${id}$` , true).draw();#}

                {#table_order_details.columns(0).search(`^345$` , true).draw();#}
                {#table_order_details.columns(0).search(`^${id}$` , true).draw();#}

                    break;

                default:
                    console.error(`Unknown action: ${action}`)

            }

        });


        $('#complaint_details tbody').on('click', 'button', function () {
            let data = table_complaints_details.row($(this).parents('tr')).data();
            let id = data['id'];

            // кнопки действий
            let action = parseInt(this.getAttribute('data-action'));
            let status = parseInt(this.getAttribute('data-status'));

            switch (action) {
                {#case 0:#}
                {#    SetNumberStatus(this, id, status);#}
                {#    break;#}
                {##}
                {#case 1:#}
                {#    ShowOrderDetails(id);#}
                {#    break;#}

                case 2:
                    // show lightbox, https://ashleydw.github.io/lightbox/
                    let screenshot_url = data.screenshot;

                    let href = document.createElement('a');
                    href.setAttribute('href', screenshot_url);
                    href.setAttribute('data-toggle', 'lightbox');

                    $(href).ekkoLightbox();
                    break;

                default:
                    console.error(`Unknown action: ${action}`)

            }

        });


        //SetStatus
        function SetNumberStatus(event, id, status) {
            console.log(id, status);
            {#let that = event;#}

            $.ajax({
                type: "POST",
                url: "{% url 'api:complaint_cancel' %}",
                // data: {service_id: that.value, checked: that.checked}
                data: {
                    id: id,
                    status: status,
                }
            }).done(function (data) {
                console.log('Good');
                table_complaints.ajax.reload(null, false); // user paging is not reset on reload

            }).fail(function () {
                console.log('Failed response');
                table_complaints.ajax.reload(null, false); // user paging is not reset on reload
            })
        }


        setInterval(function () {
            table_complaints.ajax.reload();
        }, 30000);

    })
</script>